---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    flux.weave.works/tag.chart-image: glob:dev-*
    flux.weave.works/automated: 'true'
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:stefanprodan/gitops-helm
    path: charts/podinfo
    ref: master
  values:
    image: hariom12/podinfo:dev-1.5.3
    replicaCount: 1
    hpa:
      enabled: false
